#!/bin/bash

# first, flush old chains
iptables -F
ip6tables -F

# block internal addressed coming from the outside
# ip v4
iptables -A INPUT -i eth2 -s 192.168.0.1/29 -j DROP
iptables -A FORWARD -i eth2 -s 192.168.0.1/29 -j DROP
# ip v6
ip6tables -A INPUT -i eth2 -s 2607:f0d0:2001:000a::/64 -j DROP
ip6tables -A FORWARD -i eth2 -s 2607:f0d0:2001:000a::/64 -j DROP

# only allow internal addresses in the internal network
iptables -A FORWARD -i eth1 -s 1192.168.0.1/29 -j ACCEPT
iptables -A FORWARD -i eth1 -j DROP

# block unique ips: 

# ip v4
# block class A networks
iptables -A INPUT  -i eth2 -s 10.0.0.0/8 -j DROP
# block class B networks
iptables -A INPUT  -i eth2 -s 172.16.0.0/12 -j DROP
# block class C networks
iptables -A INPUT  -i eth2 -s 192.168.0.0/16 -j DROP
# block class D multicast addresses
iptables -A INPUT -i eth2 -s 224.0.0.0/4 -j DROP
# block class E reserved IP addresses.
iptables -A INPUT -i eth2 -s 240.0.0.0/5 -j DROP

# ip v6
ip6tables -A INPUT -i eth2 -s FC00::/7 -j DROP
ip6tables -A FORWARD -i eth2 -s FC00::/7 -j DROP

# block addressed which mirror the loopback interface
# ip v4
iptables -A INPUT -i lo -d 127.0.0.0/8 -j DROP
iptables -A INPUT -i lo -d x.x.x.255 -j DROP
# ip v6
ip6tables -A INPUT -i lo -d ::1/128 -j DROP
